import React from 'react';

import { NextPage } from 'next';
import Head from 'next/head';

import { AUTH_EID_WEBSITE_URL } from '~/constants/configConstants';
import { faqPagePaths } from '~/constants/pathsConstants';
import { FaqAccordionComponent } from '~/components/FaqAccordion/FaqAccordionComponent';
import { LinkComponent } from '~/components/Link/LinkComponent';
import { OpenGraphComponent } from '~/components/OpenGraph/OpenGraphComponent';
import { FaqLayout } from '~/layouts/Faq/FaqLayout';

import style from './style.module.scss';

const Account: NextPage = () => {
  return (
    <>
      <Head>
        <title>FAQ - Account</title>

        <OpenGraphComponent title="FAQ" description="Account" />
      </Head>

      <FaqLayout headline="Account" links={faqPagePaths}>
        <FaqAccordionComponent headline="Registration & Management" defaultValue>
          <p className={style.faqText}>
            Leverex supports two account types. Corporate accounts and individual accounts.
          </p>

          <p className={style.faqText}>
            Leverex aims to make account management simple, smooth, and compliant. To achieve these goals, we require
            that all interactions with Leverex take place using the Authenticate eID mobile app.
          </p>

          <p className={style.faqText}>
            Authenticate eID sets a new standard for handling initial KYC and ongoing account management by providing a
            single point of entry for maintaining easier, safer and better customer experiences.
          </p>

          <p className={style.faqText}>
            Please being your onboarding journey by downloading Authenticate eID&nbsp;
            <LinkComponent href={AUTH_EID_WEBSITE_URL}>here</LinkComponent>.
          </p>
        </FaqAccordionComponent>

        <FaqAccordionComponent headline="Currencies">
          <p className={style.faqText}>Leverex offers accounts in Liquid USDT only.</p>

          <p className={style.faqText}>All settlements, payments, and balances will be kept in USDT.</p>
        </FaqAccordionComponent>

        <FaqAccordionComponent headline="Address Whitelisting">
          <p className={style.faqText}>
            Leverex permits withdrawals to pre-registered addresses which have been submitted through Authenticate eID
            and signed for by the client.
          </p>

          <p className={style.faqText}>Addresses must be blinded.</p>
        </FaqAccordionComponent>

        <FaqAccordionComponent headline="History">
          <p className={style.faqText}>
            The history section displays the accounts trade history, deposits and withdrawals, and fees.
          </p>

          <p className={style.faqText}>
            The trade history tab includes the date, acquirer, status, instrument, quantity, price, and type.
          </p>

          <p className={style.faqText}>
            The fees page shows the specifics about how much fees have been deducted from activities and trades.
          </p>

          <p className={style.faqText}>
            The deposits and withdrawals sections display all external account debits and credits.
          </p>

          <p className={style.faqText}>Reports can be generated and downloaded on demand.</p>
        </FaqAccordionComponent>

        <FaqAccordionComponent headline="Statements">
          <p className={style.faqText}>
            Statements are generated by the user on demand. The statements provide you with detailed information
            relating to the value of your portfolio, deposits, withdrawals, trades, volumes, end-of-day pricing and
            realized prices.
          </p>

          <p className={style.faqText}>Statements may be used for reporting purposes.</p>
        </FaqAccordionComponent>
      </FaqLayout>
    </>
  );
};

export default Account;
